apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-longhorn
spec:
  package: ghcr.io/hops-ops/helm-longhorn:{{ .Values.version }}
  {{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
  {{- end }}
---
{{- if .Values.skipDependencyResolution }}
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-go-templating:v0.10.0
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.6.0
{{- end }}
