name: on-push-main

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.13.0
    with:
      examples: |
        [
          { "example": "examples/longhorns/minimal.yaml" },
          { "example": "examples/longhorns/standard.yaml" }
        ]
      api_path: apis/longhorns
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.13.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.13.0

  version-and-tag:
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflows-crossplane/.github/workflows/version-and-tag.yaml@v2.13.0
    secrets: inherit
